[package]
name = "reselim/flipper"
version = "1.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.0"
Flipper = "reselim/flipper@2.0.0"